# Generated by Django 4.2.13 on 2024-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_alter_profile_skills_delete_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, '러너'), (2, '티쳐')], null=True),
        ),
    ]
