# Generated by Django 5.0.6 on 2024-06-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField()),
                ('plan', models.TextField()),
                ('method', models.CharField(choices=[('free', '무료 티칭'), ('paid', '유료 티칭')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plans', to='accounts.profile')),
            ],
        ),
    ]
