# Generated by Django 4.2.13 on 2024-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_personality_profile_personalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
