# Generated by Django 4.2.13 on 2024-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='profile_emoji',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
