# Generated by Django 4.2.13 on 2024-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_plan',
            field=models.TextField(null=True),
        ),
    ]
