# Generated by Django 4.2.13 on 2024-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_learner_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='my_teachers',
            field=models.ManyToManyField(related_name='my_learners', to='profiles.teacher'),
        ),
    ]
