# Generated by Django 4.2.13 on 2024-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_learner_my_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_appealed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
