# Generated by Django 4.2.13 on 2024-07-03 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_learner_my_teachers'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewForm',
            new_name='Review',
        ),
    ]
