# Generated by Django 4.2.13 on 2024-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='내용'),
        ),
    ]
